### ISSUE TITLE
update readme by explaining the project details

### ISSUE THREAD

**Issue by tejaswini22199** [tejaswini22199/KnowledgeShare#1]

**Comment by kunaljain0212** [comment]
Can I work on this, please? @tejaswini22199

**Comment by roli25** [comment]
can I also work on this?

**Comment by tejaswini22199** [comment]
@kunaljain0212  any updates. If @kunaljain0212  doesn't work on this I'll assign you

**Comment by awantika10** [comment]
Hey ! Can I work on this ?

**Comment by roli25** [comment]
ok sure!
