### ISSUE TITLE
make it 2 page website

### ISSUE THREAD

**Issue by tejaswini22199** [tejaswini22199/KnowledgeShare#20]
At present there is only one page in the UI make it a 2 page file by clicking a button or link make it redirect to other page

**Comment by Naman-1234** [comment]
@tejaswini22199  I would like to contribute on this issue sir.

**Comment by Naman-1234** [comment]
Sir sorry to disturb but its a little ambiguous about your 2 page,like Do u want a list to be in another page just below than add or clear button or something else,Pls describe it.

**Comment by tejaswini22199** [comment]
I want the list of resources in another page. Please don't call me sir. Call me didi if you want

**Comment by Naman-1234** [comment]
Ok Got it.
