### ISSUE TITLE
Asking yes or no on clicking clear list button

### ISSUE THREAD

**Issue by Naman-1234** [tejaswini22199/KnowledgeShare#27]
What i meant is if u see your list then as soon as user clicks clear  button ,he/she is left with no other option than to click on Ok,on the other hand Case should be that user should be given Option of yes/no

@tejaswini22199  I would like to contribute to this.

**Comment by tejaswini22199** [comment]
Do you want to design a pop up whenever user clears list to clear or not??

**Comment by Naman-1234** [comment]
@tejaswini22199  Yes.

**Comment by Navpreet1234** [comment]
@tejaswini22199 I would Like to contribute to this issue.
