### ISSUE TITLE
code of conduct ,contributors in readme ,This feature is needed

### ISSUE THREAD

**Issue by tejaswini22199** [tejaswini22199/KnowledgeShare#28]

**Comment by PinRathod** [comment]
@tejaswini22199 You want to add Code of conduct file? If yes then I want to work on it..

**Comment by Nivedita967** [comment]
If you want to add contributors in readme, then I can work on this.

**Comment by tejaswini22199** [comment]
I want to make this as a dynamic one by using all contributors bot you can search about it. If you can do this then go ahead. Please add both code of conduct and this feature because this is a simple issue.
