### ISSUE TITLE
suggest ideas for adding new features

### ISSUE THREAD

**Issue by tejaswini22199** [tejaswini22199/KnowledgeShare#3]
add your ideas in idea.md provided

**Comment by Godzilla5111** [comment]
Maybe you can simply separate the pages, such as one will contain all the resources, and another page will contain the form to add the resources and some basic instructions for the user to follow while contributing.

**Comment by Godzilla5111** [comment]
Also, you can focus a bit on enhancing the UI and use simple bootstrap elements, say jumbotron and refine the pages.

**Comment by Godzilla5111** [comment]
@tejaswini22199, if you wish, I can create an 'ideas/suggestions' file where any visitor can put up their ideas. You can refer that and incorporate the ones into your project which you feel like doing. What do yo say?

**Comment by tejaswini22199** [comment]
@Godzilla5111  go ahead. If you feel like solving the issues you can solve them too.

**Comment by Godzilla5111** [comment]
Sure @tejaswini22199! Please assign it to me. I will start contributing as soon as the coding period starts!

**Comment by Godzilla5111** [comment]
Thanks, @tejaswini22199 😊

**Comment by mastershailesh1234** [comment]
can I style the page? means can i add more css and beautify it?

**Comment by tejaswini22199** [comment]
sure @mastershailesh1234  I'll create that issue and assign it to you.

**Comment by mastershailesh1234** [comment]
thank you @tejaswini22199 😁

**Comment by Godzilla5111** [comment]
Hey @tejaswini22199, please check the PR👍

**Comment by mk143c** [comment]
Hey @tejaswini22199 can i work on buttons like reduce the size and fixed them in one row.
