### ISSUE TITLE
Enhancing ui using css

### ISSUE THREAD

**Issue by tejaswini22199** [tejaswini22199/KnowledgeShare#6]

**Comment by mastershailesh1234** [comment]
i would like to work on this issue!!!

**Comment by mastershailesh1234** [comment]
hey @tejaswini22199 i have sent a PR request. kindly go though it.

**Comment by roli25** [comment]
Can I contribute in this?

**Comment by tejaswini22199** [comment]
yes

**Comment by Navpreet1234** [comment]
@tejaswini22199 plz assign this issue to me

**Comment by roli25** [comment]
@tejaswini22199 i have made a pr . Do suggest changes.

**Comment by tejaswini22199** [comment]
I don't think there is much change you just changed button color.

**Comment by roli25** [comment]
I also added a favicon but will remove it now. What kind of ui you are expecting?

**Comment by tejaswini22199** [comment]
The present UI is fine but I want some other ideas to change the layout. There  is no restriction but I was not expecting small changes like the button color and all.
