### ISSUE TITLE
Add a favicon 

### ISSUE THREAD

**Issue by Godzilla5111** [tejaswini22199/KnowledgeShare#7]
Favicon is missing and needs to be added.

**Comment by Godzilla5111** [comment]
Hey @tejaswini22199 , I will work on this and add a suitable favicon. Please assign it to me.

**Comment by Godzilla5111** [comment]
I will send a PR after adding the favicon.

**Comment by tejaswini22199** [comment]
I think you are already working with other issue right. Did you work on that

**Comment by Godzilla5111** [comment]
Ya that needs adding a file. I will do that as well. Since this one's easy, I will complete this in a minute and work on the previous one✌

**Comment by Godzilla5111** [comment]
Thanks👍
