### ISSUE TITLE
Adding resources

### ISSUE THREAD

**Issue by tejaswini22199** [tejaswini22199/KnowledgeShare#8]
Create a folder named resources and add resources related to Machine Learning web development android Cp interview questions etc.,
Folder structure:
root/Resources/{File name}/readme.md

**Comment by tejaswini22199** [comment]
Take a topic and comment down below.

**Comment by Vrindagupta6828** [comment]
@tejaswini22199 I would like to add resources regarding cp

**Comment by Vrindagupta6828** [comment]
@tejaswini22199 Can you also please elaborate what kind of resources you want?? Important questions, Coding sites, Learning platforms???

**Comment by tejaswini22199** [comment]
I want topic wise if its related to cp like linkedlist graphs etc. along with that add coding sites to practice.Add blogs where the data structures are explained clearly.

**Comment by Vrindagupta6828** [comment]
@tejaswini22199 i will add topics folder and inside that link to a blog and a practice site

**Comment by tejaswini22199** [comment]
Okay go-ahead @Vrindagupta6828

**Comment by Nivedita967** [comment]
I would like to add resources related to Web Development.

**Comment by tejaswini22199** [comment]
sure go ahead @Nivedita967  create a folder named resources and add webdevelopment.md file. Add resources in that file.

**Comment by Nivedita967** [comment]
Okay

**Comment by Vkishor18** [comment]
Hey @tejaswini22199  can we add resources related to a particular subject or language(like Java, Python, etc.) also or do we have to choose from the options you mentioned above?

**Comment by tejaswini22199** [comment]
@Vkishor18  sure you can add related to language as well I'm collecting them to render on page later

**Comment by Vkishor18** [comment]
Okay @tejaswini22199  I will add resources related to Java.

**Comment by Navpreet1234** [comment]
@tejaswini22199  please assign this issue to me.I want to contribute for cp interview questions.
