### ISSUE TITLE
Add Resources for Computer Vision and NLP

### ISSUE THREAD

**Issue by yashasvimisra2798** [tejaswini22199/KnowledgeShare#81]

**Comment by yashasvimisra2798** [comment]
I want to work on this. Please assign this to me.

**Comment by tejaswini22199** [comment]
Add basic projects also because this is small issue. So if you add resource related to projects(mini) or major it would be helpful

**Comment by yashasvimisra2798** [comment]
![ss](https://user-images.githubusercontent.com/54177363/103542939-bc51d180-4ec3-11eb-857e-c389e657f0c7.PNG)
![ss2](https://user-images.githubusercontent.com/54177363/103542945-bd82fe80-4ec3-11eb-8ecc-9de209f8706d.PNG)
![ss3](https://user-images.githubusercontent.com/54177363/103542948-be1b9500-4ec3-11eb-90aa-76d8f6cf66e8.PNG)

**Comment by yashasvimisra2798** [comment]
@tejaswini22199 please merge my PR's
